services:
  sunshine:
    build: .
    ports:
      - "3000:80"
    volumes:
      - sunshine_storage:/rails/storage
      - sunshine_log:/rails/log
      - sunshine_tmp:/rails/tmp
    environment:
      - RAILS_ENV=production
      - RAILS_MAX_THREADS=5
      - RAILS_LOG_TO_STDOUT=true
      - MQTT_HOST=mqtt
      - MQTT_PORT=1883
      - MQTT_USER=sunshine
      - MQTT_PASSWORD=development
      - REDIS_URL=redis://redis:6379/1
      - SECRET_KEY_BASE=${SECRET_KEY_BASE:-$(openssl rand -hex 64)}
      - SOLID_QUEUE_POLLING_INTERVAL=1
    depends_on:
      - mqtt
      - redis

  # radio-gaga:
  #   build:
  #     context: ../reunu-radio-gaga
  #   environment:
  #     - MQTT_HOST=mqtt
  #     - MQTT_PORT=1883
  #     - MQTT_USER=sunshine
  #     - MQTT_PASSWORD=development
  #     - CLOUD_WS_ENDPOINT=ws://web:3000/api/v1/ws
  #     - DEVICE_ID=REUNU-TEST-VOID
  #     - UPLOAD_RATE=5
  #   volumes:
  #     - ../radio-gaga:/app
  #   depends_on:
  #     - sunshine
  #     - mqtt
  
  mqtt:
    image: eclipse-mosquitto:2
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./config/mosquitto:/mosquitto/config/
      - ./config/mqtt_certs:/mosquitto/certs/
      - mqtt_data:/mosquitto/data
      - mqtt_log:/mosquitto/log

  redis:
    image: redis:7
    ports:
      - "6379"
    volumes:
      - redis_data:/data

volumes:
  sunshine_storage:
  sunshine_log:
  sunshine_tmp:
  redis_data:
  mqtt_data:
  mqtt_log:
