service: sunshine
image: teal-bauer/sunshine

servers:
  web:
    - 178.63.144.127
  job:
    hosts:
      - 178.63.144.127
    cmd: bin/jobs
  mqtt:
    hosts:
      - 178.63.144.127
    cmd: bin/mqtt
  
builder:
  arch: amd64
  remote: ssh://root@rescoot.org

proxy:
  ssl: true
  hosts:
    - rescoot.org
    - sunshine.rescoot.org
    - unu.rescoot.org
    - unu.cloud.rescoot.org

registry:
  server: ghcr.io
  username: teal-bauer
  password:
    - KAMAL_REGISTRY_PASSWORD

env:
  secret:
    - RAILS_MASTER_KEY
    - MQTT_PASSWORD
    - SMTP_PASSWORD
  clear:
    RAILS_ENV: production
    RAILS_LOG_TO_STDOUT: true
    REDIS_URL: redis://sunshine-redis:6379/1
    MQTT_HOST: mqtt.sunshine.rescoot.org
    MQTT_PORT: 8883
    MQTT_SSL: true
    MQTT_USERNAME: cloud_service
    MQTT_CA_CRT_PATH: config/mqtt_certs/ca.crt
    MQTT_SERVER_CRT_PATH: config/mqtt_certs/server/server.crt
    MQTT_SERVER_KEY_PATH: config/mqtt_certs/server/server.key

accessories:
  mqtt:
    image: eclipse-mosquitto:latest
    roles:
      - web
    files:
      - config/mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - config/mosquitto/acl:/mosquitto/config/acl
      - config/mqtt_certs/ca.crt:/mosquitto/certs/ca.crt
      - config/mqtt_certs/server/server.crt:/mosquitto/certs/server/server.crt
      - config/mqtt_certs/server/server.key:/mosquitto/certs/server/server.key
    volumes:
      - /etc/mosquitto/config/passwd:/mosquitto/config/passwd
      - /etc/mosquitto/data:/mosquitto/data
      - /etc/mosquitto/log:/mosquitto/log
      - /etc/mosquitto/certs:/mosquitto/certs
    options:
      publish:
        - "1883:1883"
        - "8883:8883"
      restart: unless-stopped

  redis:
    image: redis:7-alpine
    roles:
      - web
    port: 127.0.0.1:6379:6379
    volumes:
      - /var/lib/redis:/data
    options:
      restart: unless-stopped

volumes:
  - "sunshine_storage:/rails/storage"
  - "/var/lib/redis:/var/lib/redis"

aliases:
  console: app exec --interactive --reuse "bin/rails console"
  shell: app exec --interactive --reuse "bash"
  logs: app logs -f
  dbc: app exec --interactive --reuse "bin/rails dbconsole"

asset_path: /rails/public/assets/
