service: sunshine
image: <%= ENV['IMAGE_NAME'] %>

servers:
  web:
    hosts:
    - <%= ENV['WEB_SERVER_IP'] %>
    env:
      MQTT_ROLE: web
  job:
    hosts:
    - <%= ENV['JOB_SERVER_IP'] %>
    cmd: bin/jobs
  mqtt:
    hosts:
    - <%= ENV['MQTT_SERVER_IP'] %>
    env:
      MQTT_ROLE: background
    cmd: bin/mqtt

builder:
  arch: amd64
  remote: ssh://<%= ENV['BUILDER_USER'] %>@<%= ENV['BUILDER_HOST'] %>

proxy:
  ssl: true
  hosts:
  - <%= ENV['PRIMARY_DOMAIN'] %>
  - <%= ENV['SUNSHINE_DOMAIN'] %>
  - <%= ENV['UNU_DOMAIN'] %>
  - <%= ENV['UNU_CLOUD_DOMAIN'] %>

registry:
  server: ghcr.io
  username:
  - KAMAL_REGISTRY_USERNAME
  password:
  - KAMAL_REGISTRY_PASSWORD

env:
  secret:
  - RAILS_MASTER_KEY
  - MQTT_PASSWORD
  - SMTP_PASSWORD
  clear:
    RAILS_ENV: production
    RAILS_LOG_TO_STDOUT: true
    REDIS_URL: redis://sunshine-redis:6379/1
    SMTP_ADDRESS: <%= ENV['SMTP_ADDRESS'] %>
    MQTT_HOST: <%= ENV['MQTT_HOST'] %>
    MQTT_PORT: <%= ENV['MQTT_PORT'] %>
    MQTT_SSL: <%= ENV['MQTT_SSL'] %>
    MQTT_USERNAME: <%= ENV['MQTT_USERNAME'] %>
    MQTT_CA_CRT_PATH: config/mqtt_certs/ca.crt
    MQTT_SERVER_CRT_PATH: config/mqtt_certs/server/server.crt
    MQTT_SERVER_KEY_PATH: config/mqtt_certs/server/server.key

accessories:
  mqtt:
    image: eclipse-mosquitto:latest
    roles:
    - web
    files:
    - config/mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
    - config/mosquitto/acl:/mosquitto/config/acl
    - config/mqtt_certs/ca.crt:/mosquitto/certs/ca.crt
    - config/mqtt_certs/server/server.crt:/mosquitto/certs/server/server.crt
    - config/mqtt_certs/server/server.key:/mosquitto/certs/server/server.key
    volumes:
    - /etc/mosquitto/data/dynamic-security.json:/mosquitto/data/dynamic-security.json
    - /etc/mosquitto/config/passwd:/mosquitto/config/passwd
    - /etc/mosquitto/data:/mosquitto/data
    - /etc/mosquitto/log:/mosquitto/log
    - /etc/mosquitto/certs:/mosquitto/certs
    options:
      publish:
      - "1883:1883"
      - "8883:8883"
      restart: unless-stopped

  redis:
    image: redis:7-alpine
    roles:
    - web
    port: 127.0.0.1:6379:6379
    volumes:
    - /var/lib/redis:/data
    options:
      restart: unless-stopped

volumes:
- "sunshine_storage:/rails/storage"
- "/var/lib/redis:/var/lib/redis"

aliases:
  console: app exec --interactive --reuse "bin/rails console"
  shell: app exec --interactive --reuse "bash"
  logs: app logs -f
  dbc: app exec --interactive --reuse "bin/rails dbconsole"

asset_path: /rails/public/assets/
