service: sunshine
image: teal-bauer/sunshine

servers:
  web:
    - 178.63.144.127
  job:
    hosts:
      - 178.63.144.127
    cmd: bin/jobs
  mqtt:
    hosts:
      - 178.63.144.127
    cmd: bin/mqtt

proxy:
  ssl: true
  hosts:
    - rescoot.org
    - sunshine.rescoot.org
    - unu.rescoot.org
    - unu.cloud.rescoot.org

registry:
  server: ghcr.io
  username: teal-bauer
  password:
    - KAMAL_REGISTRY_PASSWORD

env:
  secret:
    - RAILS_MASTER_KEY
    - MQTT_PASSWORD
    - SMTP_PASSWORD
    - MQTT_CA_CRT
    - MQTT_SERVER_CRT
    - MQTT_SERVER_KEY
  clear:
    RAILS_ENV: production
    RAILS_LOG_TO_STDOUT: true
    MQTT_HOST: mqtt.sunshine.rescoot.org
    MQTT_PORT: 8883
    MQTT_USERNAME: cloud_service
    REDIS_URL: redis://sunshine-redis:6379/1

accessories:
  mqtt:
    image: eclipse-mosquitto:latest
    roles:
      - web
    port: "1883"
    options:
      publish:
        - "1883:1883"
        - "8883:8883"
    volumes:
      - /etc/mosquitto/config:/mosquitto/config
      - /etc/mosquitto/data:/mosquitto/data
      - /etc/mosquitto/log:/mosquitto/log
      - /etc/mosquitto/certs:/mosquitto/certs
    options:
      restart: unless-stopped

  redis:
    image: redis:7-alpine
    roles:
      - web
    port: 127.0.0.1:6379:6379
    volumes:
      - /var/lib/redis:/data
    options:
      restart: unless-stopped

volumes:
  - "sunshine_storage:/rails/storage"
  - "/var/lib/redis:/var/lib/redis"
  - "/etc/mosquitto:/etc/mosquitto"

builder:
  arch: amd64

aliases:
  console: app exec --interactive --reuse "bin/rails console"
  shell: app exec --interactive --reuse "bash"
  logs: app logs -f
  dbc: app exec --interactive --reuse "bin/rails dbconsole"

asset_path: /rails/public/assets/
