production:
  # periodic_cleanup:
  #   class: CleanSoftDeletedRecordsJob
  #   queue: background
  #   args: [ 1000, { batch_size: 500 } ]
  #   schedule: every hour
  # periodic_command:
  #   command: "SoftDeletedRecord.due.delete_all"
  #   priority: 2
  #   schedule: at 5am every day
  telemetry_archival:
    class: TelemetryArchivalJob
    queue: background
    schedule: at 3am every day
  telemetry_cache_cleanup:
    command: "Rails.cache.cleanup"
    priority: 1
    schedule: every 6 hours
  trip_finalization:
    class: TripFinalizationJob
    queue: background
    schedule: every 5 minutes
  leaderboard_achievement:
    class: LeaderboardAchievementJob
    queue: background
    schedule: "@weekly"
