# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: unu/v1/scooter_event.proto

require "google/protobuf"

require "google/protobuf/struct_pb"
require "google/protobuf/timestamp_pb"
require "unu/v1/scooter_state_pb"
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("unu/v1/scooter_event.proto", syntax: :proto3) do
    add_message "protos.unu.v1.ScooterEventBulk" do
      repeated :events, :message, 1, "protos.unu.v1.ScooterEvent"
    end
    add_message "protos.unu.v1.ScooterEvent" do
      optional :ts, :message, 1, "google.protobuf.Timestamp"
      optional :event, :message, 2, "protos.unu.v1.ScooterEvent.GenericEvent"
      optional :state, :message, 3, "protos.unu.v1.ScooterState"
    end
    add_message "protos.unu.v1.ScooterEvent.GenericEvent" do
      optional :active, :bool, 1
      optional :event_code, :string, 2
      optional :info, :message, 3, "google.protobuf.Struct"
    end
  end
end

module Protos
  module Unu
    module V1
      ScooterEventBulk = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("protos.unu.v1.ScooterEventBulk").msgclass
      ScooterEvent = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("protos.unu.v1.ScooterEvent").msgclass
      ScooterEvent::GenericEvent = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("protos.unu.v1.ScooterEvent.GenericEvent").msgclass
    end
  end
end
